// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: proto/play.proto

package play

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPlayByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetPlayByIdRequest) Reset() {
	*x = GetPlayByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_play_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayByIdRequest) ProtoMessage() {}

func (x *GetPlayByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_play_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayByIdRequest.ProtoReflect.Descriptor instead.
func (*GetPlayByIdRequest) Descriptor() ([]byte, []int) {
	return file_proto_play_proto_rawDescGZIP(), []int{0}
}

func (x *GetPlayByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPlayByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetPlayByIdResponse) Reset() {
	*x = GetPlayByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_play_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayByIdResponse) ProtoMessage() {}

func (x *GetPlayByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_play_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayByIdResponse.ProtoReflect.Descriptor instead.
func (*GetPlayByIdResponse) Descriptor() ([]byte, []int) {
	return file_proto_play_proto_rawDescGZIP(), []int{1}
}

func (x *GetPlayByIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPlayByIdResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAllPlaysRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllPlaysRequest) Reset() {
	*x = GetAllPlaysRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_play_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllPlaysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPlaysRequest) ProtoMessage() {}

func (x *GetAllPlaysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_play_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPlaysRequest.ProtoReflect.Descriptor instead.
func (*GetAllPlaysRequest) Descriptor() ([]byte, []int) {
	return file_proto_play_proto_rawDescGZIP(), []int{2}
}

type GetAllPlaysResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Plays []*GetPlayByIdResponse `protobuf:"bytes,1,rep,name=plays,proto3" json:"plays,omitempty"`
}

func (x *GetAllPlaysResponse) Reset() {
	*x = GetAllPlaysResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_play_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllPlaysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPlaysResponse) ProtoMessage() {}

func (x *GetAllPlaysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_play_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPlaysResponse.ProtoReflect.Descriptor instead.
func (*GetAllPlaysResponse) Descriptor() ([]byte, []int) {
	return file_proto_play_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllPlaysResponse) GetPlays() []*GetPlayByIdResponse {
	if x != nil {
		return x.Plays
	}
	return nil
}

type CreatePlayRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreatePlayRequest) Reset() {
	*x = CreatePlayRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_play_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayRequest) ProtoMessage() {}

func (x *CreatePlayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_play_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayRequest.ProtoReflect.Descriptor instead.
func (*CreatePlayRequest) Descriptor() ([]byte, []int) {
	return file_proto_play_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePlayRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreatePlayResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *CreatePlayResponse) Reset() {
	*x = CreatePlayResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_play_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayResponse) ProtoMessage() {}

func (x *CreatePlayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_play_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayResponse.ProtoReflect.Descriptor instead.
func (*CreatePlayResponse) Descriptor() ([]byte, []int) {
	return file_proto_play_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePlayResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatePlayResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_play_proto protoreflect.FileDescriptor

var file_proto_play_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6c, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x24, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x50,
	0x6c, 0x61, 0x79, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61,
	0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x41, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2a, 0x0a, 0x05, 0x70, 0x6c, 0x61, 0x79, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x70, 0x6c, 0x61, 0x79, 0x73, 0x22, 0x27, 0x0a, 0x11,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x6c, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32,
	0xb8, 0x01, 0x0a, 0x0b, 0x50, 0x6c, 0x61, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x38, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x42, 0x79, 0x49, 0x64, 0x12, 0x13,
	0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x12, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61,
	0x79, 0x12, 0x12, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c,
	0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f,
	0x70, 0x6c, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_play_proto_rawDescOnce sync.Once
	file_proto_play_proto_rawDescData = file_proto_play_proto_rawDesc
)

func file_proto_play_proto_rawDescGZIP() []byte {
	file_proto_play_proto_rawDescOnce.Do(func() {
		file_proto_play_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_play_proto_rawDescData)
	})
	return file_proto_play_proto_rawDescData
}

var file_proto_play_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_play_proto_goTypes = []interface{}{
	(*GetPlayByIdRequest)(nil),  // 0: GetPlayByIdRequest
	(*GetPlayByIdResponse)(nil), // 1: GetPlayByIdResponse
	(*GetAllPlaysRequest)(nil),  // 2: GetAllPlaysRequest
	(*GetAllPlaysResponse)(nil), // 3: GetAllPlaysResponse
	(*CreatePlayRequest)(nil),   // 4: CreatePlayRequest
	(*CreatePlayResponse)(nil),  // 5: CreatePlayResponse
}
var file_proto_play_proto_depIdxs = []int32{
	1, // 0: GetAllPlaysResponse.plays:type_name -> GetPlayByIdResponse
	0, // 1: PlayService.GetPlayById:input_type -> GetPlayByIdRequest
	2, // 2: PlayService.GetAllPlays:input_type -> GetAllPlaysRequest
	4, // 3: PlayService.CreatePlay:input_type -> CreatePlayRequest
	1, // 4: PlayService.GetPlayById:output_type -> GetPlayByIdResponse
	3, // 5: PlayService.GetAllPlays:output_type -> GetAllPlaysResponse
	5, // 6: PlayService.CreatePlay:output_type -> CreatePlayResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_play_proto_init() }
func file_proto_play_proto_init() {
	if File_proto_play_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_play_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_play_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_play_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllPlaysRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_play_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllPlaysResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_play_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlayRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_play_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlayResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_play_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_play_proto_goTypes,
		DependencyIndexes: file_proto_play_proto_depIdxs,
		MessageInfos:      file_proto_play_proto_msgTypes,
	}.Build()
	File_proto_play_proto = out.File
	file_proto_play_proto_rawDesc = nil
	file_proto_play_proto_goTypes = nil
	file_proto_play_proto_depIdxs = nil
}
